### ISSUE TITLE
demo 中第一张如果是视频直接报错闪退

### ISSUE THREAD

**Issue by 007xiaoyang** [yulu1121/VideoPhotoPlay#3]
复现：
initData()中列表如果是第一张视频文件
报错信息：
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.anssy.videophotoplay/com.anssy.videophotoplay.MainActivity}: java.lang.ClassCastException: com.github.videophotoplay.videoplay.AdvanceImageView cannot be cast to com.github.videophotoplay.videoplay.AdvanceVideoView
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                                    	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)

**Comment by yulu1121** [comment]
implementation 'com.github.yulu1121.VideoPhotoPlay:videophoto:1.1.7'  最新的版本修复了这个问题
